### ISSUE TITLE
大佬，可以卖我一下历史的北向资金吗

### ISSUE THREAD

**Issue by kangseung** [jarekqin/north_bound#1]
QQ529767119

**Comment by jarekqin** [comment]
不好意思，刚看邮件。。一直都很忙，你要北向资金？？？
没看懂

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jiangsheng<mailto:notifications@github.com>
发送时间: 2021年1月8日 15:36
收件人: jarekqin/north_bound<mailto:north_bound@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [jarekqin/north_bound] 大佬，可以卖我一下历史的北向资金吗 (#1)


QQ529767119

―

**Comment by kangseung** [comment]
是的呀，我需要历史数据，现在我也在每天扒数据，但是历史的北向资金数据没有。。可以卖我吗？？  给个联系方式呗

**Comment by jarekqin** [comment]
额。。这个我的github里的程序可以直接拔的啊，不需要买吧？？


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jiangsheng<mailto:notifications@github.com>
发送时间: 2021年1月20日 15:42
收件人: jarekqin/north_bound<mailto:north_bound@noreply.github.com>
抄送: Jarekqin<mailto:loveboa007@live.cn>; Comment<mailto:comment@noreply.github.com>
主题: Re: [jarekqin/north_bound] 大佬，可以卖我一下历史的北向资金吗 (#1)


是的呀，我需要历史数据，现在我也在每天扒数据，但是历史的北向资金数据没有。。可以卖我吗？？ 给个联系方式呗

―

**Comment by kangseung** [comment]
你的这个程序只能爬当天的，我需要历史的数据。。

**Comment by jarekqin** [comment]
历史的都在公司数据库，我明天看看吧，我这个程序也能回溯历史啊，输入日期就行了


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jiangsheng<mailto:notifications@github.com>
发送时间: 2021年1月25日 15:38
收件人: jarekqin/north_bound<mailto:north_bound@noreply.github.com>
抄送: Jarekqin<mailto:loveboa007@live.cn>; Comment<mailto:comment@noreply.github.com>
主题: Re: [jarekqin/north_bound] 大佬，可以卖我一下历史的北向资金吗 (#1)


你的这个程序只能爬当天的，我需要历史的数据。。

―

**Comment by kangseung** [comment]
不行的吧，我需要的是分钟北向的数据。这个地址貌似不能下载历史数据
`cookies, headers, params = define_basic_infom()
    try:
        response = requests.get('http://push2.eastmoney.com/api/qt/kamt.rtmin/get', headers=headers, params=params,
                                cookies=cookies, verify=False)
    except requests.exceptions.ConnectionError:
        while True:
            response = requests.get('http://push2.eastmoney.com/api/qt/kamt.rtmin/get', headers=headers, params=params,
                                    cookies=cookies, verify=False)
            if response.status_code == 200:
                break
`

**Comment by jarekqin** [comment]
分钟级我这边也没有抓，主要都在服务器上，服务器的数据都是公司的，不是我个人的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jiangsheng<mailto:notifications@github.com>
发送时间: 2021年1月26日 19:27
收件人: jarekqin/north_bound<mailto:north_bound@noreply.github.com>
抄送: Jarekqin<mailto:loveboa007@Live.cn>; Comment<mailto:comment@noreply.github.com>
主题: Re: [jarekqin/north_bound] 大佬，可以卖我一下历史的北向资金吗 (#1)


不行的吧，我需要的是分钟北向的数据。这个地址貌似不能下载历史数据
cookies, headers, params = define_basic_infom() try: response = requests.get('http://push2.eastmoney.com/api/qt/kamt.rtmin/get', headers=headers, params=params, cookies=cookies, verify=False) except requests.exceptions.ConnectionError: while True: response = requests.get('http://push2.eastmoney.com/api/qt/kamt.rtmin/get', headers=headers, params=params, cookies=cookies, verify=False) if response.status_code == 200: break

―

**Comment by kangseung** [comment]
好的吧。。
